
all: 
	cd anim; make
	cd emu; make
	cd macintosh; make
	cd sdl_gol; make
	cd snake; make
	cd gobang; make
	cd mandelbrot; make
	cd calculator; make
	cd saver; make

clean: 
	cd anim; make clean
	cd emu; make clean
	cd macintosh; make clean
	cd sdl_gol; make clean
	cd snake; make clean
	cd gobang; make clean
	cd mandelbrot; make clean
	cd calculator; make clean
	cd saver; make clean
